<?php

use Illuminate\Support\ServiceProvider;
use Illuminate\Routing\Router;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MainController;
use App\Http\Controllers\NewFeaturesController;
use App\Http\Middleware\UserAuthenticated;
use App\Http\Middleware\AllAuthenticated;
use App\Http\Middleware\AdminAuthenticated;
use App\Http\Middleware\EmpAuthenticated;
use App\Http\Middleware\AdminHRMAuthenticated;
use App\Http\Middleware\AdminHRMHODAuthenticated;
use App\Http\Middleware\AdminHRMHODEmpAuthenticated;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
$router->aliasMiddleware('authUser', UserAuthenticated::class);
$router->aliasMiddleware('authAll', AllAuthenticated::class);
$router->aliasMiddleware('authAdmin', AdminAuthenticated::class);
$router->aliasMiddleware('authAdminHRM', AdminHRMAuthenticated::class);
$router->aliasMiddleware('authAdminHRMHOD', AdminHRMHODAuthenticated::class);
$router->aliasMiddleware('authAdminHRMHODEmp', AdminHRMHODEmpAuthenticated::class);
$router->aliasMiddleware('authEmp', EmpAuthenticated::class);
Route::match(['get', 'post'], '/', [MainController::class, 'index']);
Route::get('/logout', [MainController::class, 'logout']);
Route::match(['get', 'post'], '/dashboard', [MainController::class, 'dashboard'])->middleware('authAll');
Route::match(['get', 'post'], '/admins', [MainController::class, 'admins'])->middleware('authAdmin');
Route::match(['get', 'post'], '/add-admin', [MainController::class, 'add_admin'])->middleware('authAdmin');
Route::match(['get', 'post'], '/deactivate-admin/{id}', [MainController::class, 'deactivate_admin'])->middleware('authAdmin');
Route::match(['get', 'post'], '/activate-admin/{id}', [MainController::class, 'activate_admin'])->middleware('authAdmin');
Route::match(['get', 'post'], '/edit-admin/{id}', [MainController::class, 'edit_admin'])->middleware('authAdmin');
Route::match(['get', 'post'], '/hr-managers', [MainController::class, 'hr_managers'])->middleware('authAdmin');
Route::match(['get', 'post'], '/add-hr-manager', [MainController::class, 'add_hr_manager'])->middleware('authAdmin');
Route::match(['get', 'post'], '/deactivate-hr-manager/{id}', [MainController::class, 'deactivate_hr_manager'])->middleware('authAdmin');
Route::match(['get', 'post'], '/activate-hr-manager/{id}', [MainController::class, 'activate_hr_manager'])->middleware('authAdmin');
Route::match(['get', 'post'], '/edit-hr-manager/{id}', [MainController::class, 'edit_hr_manager'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/employees', [MainController::class, 'employees'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-employee', [MainController::class, 'add_employee'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-employee-leave', [MainController::class, 'add_employee_leave'])->middleware('authAdminHRMHODEmp');
Route::match(['get', 'post'], '/deactivate-employee/{id}', [MainController::class, 'deactivate_employee'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/activate-employee/{id}', [MainController::class, 'activate_employee'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/designations', [MainController::class, 'designations'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-designation', [MainController::class, 'add_designations'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-designation/{id}', [MainController::class, 'edit_designation'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/departments', [MainController::class, 'departments'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-department', [MainController::class, 'add_department'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-department/{id}', [MainController::class, 'edit_department'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-employee/{id}', [MainController::class, 'edit_employee'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-employee-basic/{id}', [MainController::class, 'edit_employee_basic'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-immigration/{id}', [MainController::class, 'add_immigration'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-immigration/{id}', [MainController::class, 'edit_immigration'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/delete-immigration/{id}', [MainController::class, 'delete_immigration'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-contact/{id}', [MainController::class, 'add_contact'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-contact/{id}', [MainController::class, 'edit_contact'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/delete-contact/{id}', [MainController::class, 'delete_contact'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-social-profile/{id}', [MainController::class, 'add_social_profile'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-document/{id}', [MainController::class, 'add_document'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-document/{id}', [MainController::class, 'edit_document'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/delete-document/{id}', [MainController::class, 'delete_document'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-qulification/{id}', [MainController::class, 'add_qulification'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-qulification/{id}', [MainController::class, 'edit_qulification'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/delete-qulification/{id}', [MainController::class, 'delete_qulification'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-work/{id}', [MainController::class, 'add_work'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-work/{id}', [MainController::class, 'edit_work'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/delete-work/{id}', [MainController::class, 'delete_work'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-bank-account/{id}', [MainController::class, 'add_bank_account'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-bank-account/{id}', [MainController::class, 'edit_bank_account'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/delete-bank-account/{id}', [MainController::class, 'delete_bank_account'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/change-employee-image/{id}', [MainController::class, 'change_employee_image'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-basic-salary/{id}', [MainController::class, 'add_basic_salary'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-basic-salary/{id}', [MainController::class, 'edit_basic_salary'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/delete-basic-salary/{id}', [MainController::class, 'delete_basic_salary'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-allowances/{id}', [MainController::class, 'add_allowances'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-allowances/{id}', [MainController::class, 'edit_allowances'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/delete-allowances/{id}', [MainController::class, 'delete_allowances'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-commissions/{id}', [MainController::class, 'add_commissions'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-commissions/{id}', [MainController::class, 'edit_commissions'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/delete-commissions/{id}', [MainController::class, 'delete_commissions'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-loan/{id}', [MainController::class, 'add_loan'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-loan/{id}', [MainController::class, 'edit_loan'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/delete-loan/{id}', [MainController::class, 'delete_loan'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-deduction/{id}', [MainController::class, 'add_deduction'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-deduction/{id}', [MainController::class, 'edit_deduction'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/delete-deduction/{id}', [MainController::class, 'delete_deduction'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-payment/{id}', [MainController::class, 'add_payment'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-payment/{id}', [MainController::class, 'edit_payment'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/delete-payment/{id}', [MainController::class, 'delete_payment'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-overtime/{id}', [MainController::class, 'add_overtime'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-overtime/{id}', [MainController::class, 'edit_overtime'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/delete-overtime/{id}', [MainController::class, 'delete_overtime'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-pension/{id}', [MainController::class, 'add_pension'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/core-hr-promotions', [MainController::class, 'core_hr_promotions'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/add-promotion', [MainController::class, 'add_promotion'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/delete-core-hr-promotion/{id}', [MainController::class, 'delete_core_hr_promotion'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/edit-core-hr-promotion/{id}', [MainController::class, 'edit_core_hr_promotion'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/core-hr-awards', [MainController::class, 'core_hr_awards'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/add-award', [MainController::class, 'add_award'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/delete-core-hr-award/{id}', [MainController::class, 'delete_core_hr_award'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/edit-core-hr-award/{id}', [MainController::class, 'edit_core_hr_award'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/core-hr-travels', [MainController::class, 'core_hr_travels'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/add-travel', [MainController::class, 'add_travel'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/delete-core-hr-travel/{id}', [MainController::class, 'delete_core_hr_travel'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/edit-core-hr-travel/{id}', [MainController::class, 'edit_core_hr_travel'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/core-hr-transfers', [MainController::class, 'core_hr_transfers'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/add-transfer', [MainController::class, 'add_transfer'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/delete-core-hr-transfer/{id}', [MainController::class, 'delete_core_hr_transfer'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/edit-core-hr-transfer/{id}', [MainController::class, 'edit_core_hr_transfer'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/core-hr-resignations', [MainController::class, 'core_hr_resignations'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/add-resignation', [MainController::class, 'add_resignation'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/delete-core-hr-resignation/{id}', [MainController::class, 'delete_core_hr_resignation'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/edit-core-hr-resignation/{id}', [MainController::class, 'edit_core_hr_resignation'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/core-hr-complaints', [MainController::class, 'core_hr_complaints'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/add-complaint', [MainController::class, 'add_complaint'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/delete-core-hr-complaint/{id}', [MainController::class, 'delete_core_hr_complaint'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/edit-core-hr-complaint/{id}', [MainController::class, 'edit_core_hr_complaint'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/core-hr-warnings', [MainController::class, 'core_hr_warnings'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/add-warning', [MainController::class, 'add_warning'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/delete-core-hr-warning/{id}', [MainController::class, 'delete_core_hr_warning'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/edit-core-hr-warning/{id}', [MainController::class, 'edit_core_hr_warning'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/core-hr-terminations', [MainController::class, 'core_hr_terminations'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/add-termination', [MainController::class, 'add_termination'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/delete-core-hr-termination/{id}', [MainController::class, 'delete_core_hr_termination'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/edit-core-hr-termination/{id}', [MainController::class, 'edit_core_hr_termination'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/view-core-hr-promotion/{id}', [MainController::class, 'view_core_hr_promotion'])->middleware('authAdminHRMHODEmp');
Route::match(['get', 'post'], '/pm-clients', [MainController::class, 'pm_clients'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-client', [MainController::class, 'add_client'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/delete-pm-client/{id}', [MainController::class, 'delete_pm_client'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-pm-client/{id}', [MainController::class, 'edit_pm_client'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/pm-projects', [MainController::class, 'pm_projects'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-project', [MainController::class, 'add_project'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/delete-pm-project/{id}', [MainController::class, 'delete_pm_project'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-pm-project/{id}', [MainController::class, 'edit_pm_project'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/pm-tasks', [MainController::class, 'pm_tasks'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-task', [MainController::class, 'add_task'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/delete-pm-task/{id}', [MainController::class, 'delete_pm_task'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-pm-task/{id}', [MainController::class, 'edit_pm_task'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/pm-tax-types', [MainController::class, 'pm_tax_types'])->middleware('authUser');
Route::match(['get', 'post'], '/add-tax-type', [MainController::class, 'add_tax_type'])->middleware('authUser');
Route::match(['get', 'post'], '/delete-pm-tax-type/{id}', [MainController::class, 'delete_pm_tax_type'])->middleware('authUser');
Route::match(['get', 'post'], '/edit-pm-tax-type/{id}', [MainController::class, 'edit_pm_tax_type'])->middleware('authUser');
Route::match(['get', 'post'], '/pm-invoices', [MainController::class, 'pm_invoices'])->middleware('authUser');
Route::match(['get', 'post'], '/pm-add-invoice', [MainController::class, 'pm_add_invoice'])->middleware('authUser');
Route::match(['get', 'post'], '/edit-pm-invoice/{id}', [MainController::class, 'edit_pm_invoice'])->middleware('authUser');
Route::match(['get', 'post'], '/delete-pm-invoice/{id}', [MainController::class, 'delete_pm_invoice'])->middleware('authUser');
Route::match(['get', 'post'], '/organization-departments', [MainController::class, 'organization_departments'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/add-organization-department', [MainController::class, 'add_organization_department'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/delete-organization-departments/{id}', [MainController::class, 'delete_organization_departments'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/edit-organization-departments/{id}', [MainController::class, 'edit_organization_departments'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/organization-locations', [MainController::class, 'organization_locations'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/add-organization-location', [MainController::class, 'add_organization_location'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/delete-organization-locations/{id}', [MainController::class, 'delete_organization_locations'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/edit-organization-locations/{id}', [MainController::class, 'edit_organization_locations'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/organization-designations', [MainController::class, 'organization_designations'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/add-organization-designation', [MainController::class, 'add_organization_designation'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/delete-organization-designations/{id}', [MainController::class, 'delete_organization_designations'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/edit-organization-designations/{id}', [MainController::class, 'edit_organization_designations'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/organization-announcements', [MainController::class, 'organization_announcements'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/add-announcement', [MainController::class, 'add_announcement'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/delete-organization-announcements/{id}', [MainController::class, 'delete_organization_announcements'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/edit-organization-announcements/{id}', [MainController::class, 'edit_organization_announcements'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/organization-company-policy', [MainController::class, 'organization_company_policy'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/add-policy', [MainController::class, 'add_policy'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/delete-organization-company-policy/{id}', [MainController::class, 'delete_organization_company_policy'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/edit-organization-company-policy/{id}', [MainController::class, 'edit_organization_company_policy'])->middleware('authAdminHRM');

Route::match(['get', 'post'], '/events', [MainController::class, 'events'])->middleware('authAdminHRMHODEmp');
Route::match(['get', 'post'], '/add-event', [MainController::class, 'add_event'])->middleware('authAdminHRMHODEmp');
Route::match(['get', 'post'], '/delete-events/{id}', [MainController::class, 'delete_events'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-events/{id}', [MainController::class, 'edit_events'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/meetings', [MainController::class, 'meetings'])->middleware('authAdminHRMHODEmp');
Route::match(['get', 'post'], '/add-meeting', [MainController::class, 'add_meeting'])->middleware('authAdminHRMHODEmp');
Route::match(['get', 'post'], '/delete-meetings/{id}', [MainController::class, 'delete_meetings'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-meetings/{id}', [MainController::class, 'edit_meetings'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/view-core-hr-award/{id}', [MainController::class, 'view_core_hr_award'])->middleware('authAdminHRMHODEmp');
Route::match(['get', 'post'], '/view-core-hr-travel/{id}', [MainController::class, 'view_core_hr_travel'])->middleware('authAdminHRMHODEmp');
Route::match(['get', 'post'], '/view-core-hr-transfer/{id}', [MainController::class, 'view_core_hr_transfer'])->middleware('authAdminHRMHODEmp');
Route::match(['get', 'post'], '/performance-goal-type', [MainController::class, 'performance_goal_type'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-goal-type', [MainController::class, 'add_goal_type'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/delete-performance-goal-type/{id}', [MainController::class, 'delete_performance_goal_type'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-performance-goal-type/{id}', [MainController::class, 'edit_performance_goal_type'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/performance-goal-tracking', [MainController::class, 'performance_goal_tracking'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-goal', [MainController::class, 'add_goal'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/delete-performance-goal-tracking/{id}', [MainController::class, 'delete_performance_goal_tracking'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-performance-goal-tracking/{id}', [MainController::class, 'edit_performance_goal_tracking'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/performance-indicator', [MainController::class, 'performance_indicator'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-indicator', [MainController::class, 'add_indicator'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/delete-performance-indicator/{id}', [MainController::class, 'delete_performance_indicator'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-performance-indicator/{id}', [MainController::class, 'edit_performance_indicator'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/performance-appraisal', [MainController::class, 'performance_appraisal'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-appraisal', [MainController::class, 'add_appraisal'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/delete-performance-appraisal/{id}', [MainController::class, 'delete_performance_appraisal'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-performance-appraisal/{id}', [MainController::class, 'edit_performance_appraisal'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/training-trainers', [MainController::class, 'training_trainers'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/delete-training-trainers/{id}', [MainController::class, 'delete_training_trainers'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/edit-training-trainers/{id}', [MainController::class, 'edit_training_trainers'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/training-type', [MainController::class, 'training_type'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/add-training-type', [MainController::class, 'add_training_type'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/delete-training-type/{id}', [MainController::class, 'delete__training_type'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/edit-training-type/{id}', [MainController::class, 'edit_training_type'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/training-list', [MainController::class, 'training_list'])->middleware('authAdminHRMHODEmp');
Route::match(['get', 'post'], '/add-training-list', [MainController::class, 'add_training_list'])->middleware('authAdminHRMHODEmp');
Route::match(['get', 'post'], '/delete-training-list/{id}', [MainController::class, 'delete_training_list'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/edit-training-list/{id}', [MainController::class, 'edit_training_list'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/finance-account-list', [MainController::class, 'finance_account_list'])->middleware('authUser');
Route::match(['get', 'post'], '/add-account', [MainController::class, 'add_account'])->middleware('authUser');
Route::match(['get', 'post'], '/delete-finance-account-list/{id}', [MainController::class, 'delete_finance_account_list'])->middleware('authUser');
Route::match(['get', 'post'], '/edit-finance-account-list/{id}', [MainController::class, 'edit_finance_account_list'])->middleware('authUser');
Route::match(['get', 'post'], '/finance-account-balances', [MainController::class, 'finance_account_balances'])->middleware('authUser');
Route::match(['get', 'post'], '/finance-payer', [MainController::class, 'finance_payer'])->middleware('authUser');
Route::match(['get', 'post'], '/add-payer', [MainController::class, 'add_payer'])->middleware('authUser');
Route::match(['get', 'post'], '/delete-finance-payer/{id}', [MainController::class, 'delete_finance_payer'])->middleware('authUser');
Route::match(['get', 'post'], '/edit-finance-payer/{id}', [MainController::class, 'edit_finance_payer'])->middleware('authUser');
Route::match(['get', 'post'], '/finance-payee', [MainController::class, 'finance_payee'])->middleware('authUser');
Route::match(['get', 'post'], '/add-payee', [MainController::class, 'add_payee'])->middleware('authUser');
Route::match(['get', 'post'], '/delete-finance-payee/{id}', [MainController::class, 'delete_finance_payee'])->middleware('authUser');
Route::match(['get', 'post'], '/edit-finance-payee/{id}', [MainController::class, 'edit_finance_payee'])->middleware('authUser');
Route::match(['get', 'post'], '/finance-deposit', [MainController::class, 'finance_deposit'])->middleware('authUser');
Route::match(['get', 'post'], '/add-deposit', [MainController::class, 'add_deposit'])->middleware('authUser');
Route::match(['get', 'post'], '/delete-finance-deposit/{id}', [MainController::class, 'delete_finance_deposit'])->middleware('authUser');
Route::match(['get', 'post'], '/edit-finance-deposit/{id}', [MainController::class, 'edit_finance_deposit'])->middleware('authUser');
Route::match(['get', 'post'], '/finance-expense', [MainController::class, 'finance_expense'])->middleware('authUser');
Route::match(['get', 'post'], '/add-expense', [MainController::class, 'add_expense'])->middleware('authUser');
Route::match(['get', 'post'], '/delete-finance-expense/{id}', [MainController::class, 'delete_finance_expense'])->middleware('authUser');
Route::match(['get', 'post'], '/edit-finance-expense/{id}', [MainController::class, 'edit_finance_expense'])->middleware('authUser');
Route::match(['get', 'post'], '/add-finance-transfer', [MainController::class, 'add_finance_transfer'])->middleware('authUser');
Route::match(['get', 'post'], '/finance-transfer', [MainController::class, 'finance_transfer'])->middleware('authUser');
Route::match(['get', 'post'], '/delete-finance-transfer/{id}', [MainController::class, 'delete_finance_transfer'])->middleware('authUser');
Route::match(['get', 'post'], '/edit-finance-transfer/{id}', [MainController::class, 'edit_finance_transfer'])->middleware('authUser');
Route::match(['get', 'post'], '/finance-transaction-history', [MainController::class, 'finance_transaction_history'])->middleware('authUser');
Route::match(['get', 'post'], '/finance-payment', [MainController::class, 'finance_payment'])->middleware('authUser');
Route::match(['get', 'post'], '/view-finance-payment/{id}', [MainController::class, 'view_finance_payment'])->middleware('authUser');
Route::match(['get', 'post'], '/assets-category', [MainController::class, 'assets_category'])->middleware('authUser');
Route::match(['get', 'post'], '/add-asset-category', [MainController::class, 'add_asset_category'])->middleware('authUser');
Route::match(['get', 'post'], '/delete-assets-category/{id}', [MainController::class, 'delete_assets_category'])->middleware('authUser');
Route::match(['get', 'post'], '/edit-assets-category/{id}', [MainController::class, 'edit_assets_category'])->middleware('authUser');
Route::match(['get', 'post'], '/assets-page', [MainController::class, 'assets'])->middleware('authUser');
Route::match(['get', 'post'], '/add-asset', [MainController::class, 'add_asset'])->middleware('authUser');
Route::match(['get', 'post'], '/delete-assets/{id}', [MainController::class, 'delete_assets'])->middleware('authUser');
Route::match(['get', 'post'], '/edit-assets/{id}', [MainController::class, 'edit_assets'])->middleware('authUser');
Route::match(['get', 'post'], '/file-manager', [MainController::class, 'file_manager'])->middleware('authAdminHRMHODEmp');
Route::match(['get', 'post'], '/add-file', [MainController::class, 'add_file'])->middleware('authAdminHRMHODEmp');
Route::match(['get', 'post'], '/delete-file-manager/{id}', [MainController::class, 'delete_file_manager'])->middleware('authAdminHRMHODEmp');
Route::match(['get', 'post'], '/edit-file-manager/{id}', [MainController::class, 'edit_file_manager'])->middleware('authAdminHRMHODEmp');
Route::match(['get', 'post'], '/file-oficial-documents', [MainController::class, 'file_oficial_documents'])->middleware('authAdminHRMHODEmp');
Route::match(['get', 'post'], '/add-official-document', [MainController::class, 'add_official_document'])->middleware('authAdminHRMHODEmp');
Route::match(['get', 'post'], '/delete-file-oficial-documents/{id}', [MainController::class, 'delete_file_oficial_documents'])->middleware('authAdminHRMHODEmp');
Route::match(['get', 'post'], '/edit-file-oficial-documents/{id}', [MainController::class, 'edit_file_oficial_documents'])->middleware('authAdminHRMHODEmp');
Route::match(['get', 'post'], '/office-shift', [MainController::class, 'office_shift'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-shift', [MainController::class, 'add_shift'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/delete-office-shift/{id}', [MainController::class, 'delete_office_shift'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-office-shift/{id}', [MainController::class, 'edit_office_shift'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/manage-holiday', [MainController::class, 'manage_holiday'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-holiday', [MainController::class, 'add_holiday'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/delete-holiday/{id}', [MainController::class, 'delete_holiday'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-holiday/{id}', [MainController::class, 'edit_holiday'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-leave', [MainController::class, 'add_leave'])->middleware('authAdminHRMHODEmp');
Route::match(['get', 'post'], '/manage-leaves', [MainController::class, 'manage_leaves'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/delete-leaves/{id}', [MainController::class, 'delete_leaves'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-leaves/{id}', [MainController::class, 'edit_leaves'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/update-attendances', [MainController::class, 'update_attendances']);
Route::match(['get', 'post'], '/attendence-get-employees', [MainController::class, 'attendence_get_employees']);
Route::match(['get', 'post'], '/get-attendence-details', [MainController::class, 'get_attendence_details']);
Route::match(['get', 'post'], '/add-attendence-details', [MainController::class, 'add_attendence_details']);
Route::match(['get', 'post'], '/edit-attendence-details/{id}', [MainController::class, 'edit_attendence_details'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/job-post', [MainController::class, 'job_post'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-job-post', [MainController::class, 'add_job_post'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/delete-job-post/{id}', [MainController::class, 'delete_job_post'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-job-post/{id}', [MainController::class, 'edit_job_post'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/hod', [MainController::class, 'hod'])->middleware('authAdmin');
Route::match(['get', 'post'], '/add-hod', [MainController::class, 'add_hod'])->middleware('authAdmin');
Route::match(['get', 'post'], '/deactivate-hod/{id}', [MainController::class, 'deactivate_hod'])->middleware('authAdmin');
Route::match(['get', 'post'], '/activate-hod/{id}', [MainController::class, 'activate_hod'])->middleware('authAdmin');
Route::match(['get', 'post'], '/edit-hod/{id}', [MainController::class, 'edit_hod'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/employee-profile/{id}', [MainController::class, 'employee_profile'])->middleware('authEmp');
Route::match(['get', 'post'], '/view-immigration/{id}', [MainController::class, 'view_immigration'])->middleware('authEmp');
Route::match(['get', 'post'], '/view-contact/{id}', [MainController::class, 'view_contact'])->middleware('authEmp');
Route::match(['get', 'post'], '/view-document/{id}', [MainController::class, 'view_document'])->middleware('authEmp');
Route::match(['get', 'post'], '/view-qulification/{id}', [MainController::class, 'view_qulification'])->middleware('authEmp');
Route::match(['get', 'post'], '/view-work/{id}', [MainController::class, 'view_work'])->middleware('authEmp');
Route::match(['get', 'post'], '/view-core-hr-resignations/{id}', [MainController::class, 'view_core_hr_resignations'])->middleware('authAdminHRMHODEmp');
Route::match(['get', 'post'], '/view-core-hr-complaint/{id}', [MainController::class, 'view_core_hr_complaint'])->middleware('authAdminHRMHODEmp');
Route::match(['get', 'post'], '/view-core-hr-warning/{id}', [MainController::class, 'view_core_hr_warning'])->middleware('authAdminHRMHODEmp');
Route::match(['get', 'post'], '/view-core-hr-termination/{id}', [MainController::class, 'view_core_hr_termination'])->middleware('authAdminHRMHODEmp');
Route::match(['get', 'post'], '/employee-leaves/{id}', [MainController::class, 'employee_leaves'])->middleware('authAdminHRMHODEmp');
Route::match(['get', 'post'], '/view-leave/{id}', [MainController::class, 'view_leave'])->middleware('authAdminHRMHODEmp');
Route::match(['get', 'post'], '/employee-project-tasks', [MainController::class, 'employee_project_tasks'])->middleware('authEmp');
Route::match(['get', 'post'], '/view-project/{id}', [MainController::class, 'view_project'])->middleware('authAdminHRMHODEmp');
Route::match(['get', 'post'], '/view-task/{id}', [MainController::class, 'view_task'])->middleware('authAdminHRMHODEmp');
Route::match(['get', 'post'], '/employee-events', [MainController::class, 'employee_events'])->middleware('authEmp');
Route::match(['get', 'post'], '/employee-meetings', [MainController::class, 'employee_meetings'])->middleware('authEmp');
Route::match(['get', 'post'], '/employee-training', [MainController::class, 'employee_training'])->middleware('authEmp');
Route::match(['get', 'post'], '/blocked-users', [MainController::class, 'blocked_users'])->middleware('authAdmin');
Route::match(['get', 'post'], '/unblock-user/{id}', [MainController::class, 'unblock_user'])->middleware('authAdmin');
Route::match(['get', 'post'], '/blocked-ips', [MainController::class, 'blocked_ips'])->middleware('authAdmin');
Route::match(['get', 'post'], '/unblock-ip/{id}', [MainController::class, 'unblock_ip'])->middleware('authAdmin');
Route::match(['get', 'post'], '/leave-types', [MainController::class, 'leave_types'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-leave-type', [MainController::class, 'add_leave_type'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-leave-type/{id}', [MainController::class, 'edit_leave_type'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/delete-leave-type/{id}', [MainController::class, 'delete_leave_type'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/update-special-leaves-deductions', [MainController::class, 'update_special_leaves_deductions'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/download-pay-slip/{id}', [MainController::class, 'download_pay_slip'])->middleware('authAdminHRMHODEmp');
Route::match(['get', 'post'], '/insert-records', [MainController::class, 'insert_records']);
Route::match(['get', 'post'], '/add-recruitment', [MainController::class, 'add_recruitment'])->middleware('authAdmin');
Route::match(['get', 'post'], '/delete-recruitment/{id}', [MainController::class, 'delete_recruitment'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-recruitment/{id}', [MainController::class, 'edit_recruitment'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-interview-update/{id}', [MainController::class, 'add_interview_update'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/add-other-update/{id}', [MainController::class, 'add_other_update'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-interview-update/{id}', [MainController::class, 'edit_interview_update'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-interview-other-update/{id}', [MainController::class, 'edit_interview_other_update'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/employment-type-history', [MainController::class, 'employment_type_history'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/change-employment-type', [MainController::class, 'change_employment_type'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/user-add-check-in-time', [MainController::class, 'user_add_check_in_time']);
Route::match(['get', 'post'], '/user-add-check-out-time', [MainController::class, 'user_add_check_out_time']);
Route::match(['get', 'post'], '/my-attendence-history', [MainController::class, 'my_attendence_history']);
Route::match(['get', 'post'], '/add-checkout-time', [MainController::class, 'add_checkout_time']);
Route::match(['get', 'post'], '/approve-user-checkout-time', [MainController::class, 'approve_user_checkout_time']);
Route::match(['get', 'post'], '/accept-chekout-time/{id}', [MainController::class, 'accept_chekout_time']);
Route::match(['get', 'post'], '/reject-chekout-time/{id}', [MainController::class, 'reject_chekout_time']);

Route::match(['get', 'post'], '/authorisers', [MainController::class, 'authorisers'])->middleware('authAdmin');
Route::match(['get', 'post'], '/add-authoriser', [MainController::class, 'add_authoriser'])->middleware('authAdmin');
Route::match(['get', 'post'], '/deactivate-authoriser/{id}', [MainController::class, 'deactivate_authoriser'])->middleware('authAdmin');
Route::match(['get', 'post'], '/activate-authoriser/{id}', [MainController::class, 'activate_authoriser'])->middleware('authAdmin');
Route::match(['get', 'post'], '/edit-authoriser/{id}', [MainController::class, 'edit_authoriser']);

Route::match(['get', 'post'], '/employee-report', [MainController::class, 'employee_report'])->middleware('authAdmin');
Route::match(['get', 'post'], '/leave-report', [MainController::class, 'leave_report'])->middleware('authAdmin');
Route::match(['get', 'post'], '/sallary-report', [MainController::class, 'sallary_report'])->middleware('authAdmin');
Route::match(['get', 'post'], '/attendance-report', [MainController::class, 'attendance_report'])->middleware('authAdmin');
Route::match(['get', 'post'], '/department-directory', [MainController::class, 'department_directory']);
Route::match(['get', 'post'], '/get-employee-details', [MainController::class, 'get_employee_details']);
Route::match(['get', 'post'], '/form-c', [MainController::class, 'form_c'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-hrm-basic/{id}', [MainController::class, 'edit_hrm_basic'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/change-hrm-image/{id}', [MainController::class, 'change_hrm_image'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-hod-basic/{id}', [MainController::class, 'edit_hod_basic'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/change-hod-image/{id}', [MainController::class, 'change_hod_image'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/edit-authoriser-basic/{id}', [MainController::class, 'edit_authoriser_basic'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/change-authoriser-image/{id}', [MainController::class, 'change_authoriser_image'])->middleware('authAdminHRMHOD');


Route::match(['get', 'post'], '/update-custom-leaves', [MainController::class, 'update_custom_leaves'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/accessories', [MainController::class, 'accessories'])->middleware('authAdmin');
Route::match(['get', 'post'], '/add-accessory', [MainController::class, 'add_accessory'])->middleware('authAdmin');
Route::match(['get', 'post'], '/delete-accessory/{id}', [MainController::class, 'delete_accessory'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/employee-add-accessory/{id}', [MainController::class, 'employee_add_accessory'])->middleware('authAdminHRMHOD');
Route::match(['get', 'post'], '/delete-employee-accessory/{id}', [MainController::class, 'delete_employee_accessory'])->middleware('authAdminHRMHOD');

Route::match(['get', 'post'], '/send-intern-mails', [MainController::class, 'send_intern_mails']);



Route::match(['get', 'post'], '/training-courses', [NewFeaturesController::class, 'training_courses'])->middleware('authAdminHRM');
Route::match(['get', 'post'], '/edit-training-course/{id}', [NewFeaturesController::class, 'edit_training_course'])->middleware('authAdminHRM');

Route::match(['get', 'post'], '/search-cvs', [NewFeaturesController::class, 'search_cvs'])->middleware('authAdminHRMHOD');